version: '3'
services:
  app:
    build: api/
#    ports:
#      - "5000:5000"
    volumes:
    - ./api:/api
  auth:
#    ports:
#    - "5001:5000"
    depends_on:
      - redis
    build: auth/
    volumes:
    - ./auth:/auth
  database:
    build: database/
#    ports:
#      - "5002:5000"
    volumes:
      - ./database:/database
  redis:
    image: redis
    command: "redis-server"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  mongo:
    volumes:
    - ./data:/data/db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert.crt:/cert.crt
      - ./nginx/cert.key:/cert.key
    ports:
      - 443:443