version: '3'
services:
  app:
    build: app/
    ports:
      - "5000:5000"
    volumes:
    - ./app:/app
  auth:
    ports:
    - "5001:5000"
    depends_on:
      - redis
    build: auth/
    volumes:
    - ./auth:/auth
  redis:
    image: redis
    command: "redis-server"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf