on: [push, pull_request]

jobs:
  build:
    name: Start project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir services/nginx/certs
          openssl req  -nodes -new -x509  -keyout services/nginx/certs/cert.key -out services/nginx/certs/cert.crt -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
          cd services
          docker-compose down || exit 0
          docker-compose up -d 
          
#   sleep:
#     needs: build
#     name: Wait for services to start
#     runs-on: self-hosted
#     steps:
#       - uses: jakejarvis/wait-action@master
#         with:
#           time: '30s'
      
  test:
    needs: build
    runs-on: self-hosted
    steps:
    - run: |
        pytest tests
